Added WeeklyProfileParameter schema
pywr/pywr-schema pull request #17
Opened 2023-10-24 06:58 UTC by s-simoncelli

2023-10-24 08:05 UTC, jetuk commented
This LGTM, but it needs `cargo fmt` running on it to pass the linting.

2023-10-24 09:49 UTC, jetuk requested changes

2023-10-24 09:49 UTC, jetuk commented on pywr_schema/src/parameters/profiles.rs
> +    pub values: Option<Vec<f64>>,
For the `MonthlyProfileParameter` we use `Option<[f64; 12]>` to force a fixed size array. Should this be  `Option<[f64; 52]>` instead? I know Pywr accepts 52 or 53 values, but always truncates it to 52.

2023-10-24 09:50 UTC, jetuk commented on pywr_schema/src/parameters/profiles.rs
> +    pub values: Option<Vec<f64>>,
Also, we should add the following fields to permit validating schemas that refer to external data or a table for the values. 

```
    #[serde(flatten)]
    pub external: Option<ExternalDataRef>,
    #[serde(flatten)]
    pub table_ref: Option<TableDataRef>,
```

2023-10-24 12:03 UTC, s-simoncelli commented on pywr_schema/src/parameters/profiles.rs
> +    pub values: Option<Vec<f64>>,
I implemented the parameter to handle 52 or 53 values. I'll change it to force 52

2023-10-24 12:16 UTC, jetuk commented on pywr_schema/src/parameters/profiles.rs
> +    pub values: Option<Vec<f64>>,
I wonder whether that could be a feature in Pywr-next? Either 52 or 53 week profile?

2023-11-28 17:13 UTC, jetuk commented
I've merged this with main. I think it is fine to leave it as a `Vec<f64>` here. We'll make the pywr-next schema more specific.

2023-11-28 17:13 UTC, jetuk approved these changes

2023-11-28 17:13 UTC, merged